<Project>

  <PropertyGroup>
    <AnalysisLevel>10.0-recommended</AnalysisLevel>
    <NoWarn>CS1591,CS8618,CS8620</NoWarn>
    <VersionPrefix>1.0</VersionPrefix>
    <Product>interlis-model-browser</Product>
    <Authors>GeoWerkstatt GmbH</Authors>
    <Company>GeoWerkstatt GmbH</Company>
    <PackageOutputPath>$(MSBuildThisFileDirectory)/artifacts</PackageOutputPath>
    <PackageProjectUrl>https://github.com/GeoWerkstatt/interlis-model-browser</PackageProjectUrl>
    <RepositoryUrl>https://github.com/GeoWerkstatt/interlis-model-browser.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup Condition=" '$(MSBuildProjectExtension)' != '.dcproj' ">
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.435">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
