services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ARKBONES
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 3001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: FIREGOAT
    volumes:
      - ./config/pgadmin4-servers.json:/pgadmin4/servers.json
  ilimodels:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=0.0.1
        - REVISION=1a2b3c4d
    environment:
      CONNECTIONSTRINGS__RepoBrowserContext: Host=db;Username=postgres;Password=ARKBONES;Database=repobrowser
    ports:
      - 8080:8080
