export const MockData = [
  {
    id: 301,
    mD5: "053cbfd27e3065371d2aae7d650d9756",
    name: "Moorlandschaften_V1",
    schemaLanguage: "ili2_3",
    file: "BAFU/replaced/Moorlandschaften_V1.ili",
    version: "2012-11-06",
    publishingDate: "2013-10-30T23:00:00Z",
    dependsOnModel: ["Units", "LocalisationCH_V1", "GeometryCHLV03_V1"],
    tags: ["24.1"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BAFU",
    technicalContact: "mailto:gis@bafu.admin.ch",
    furtherInformation: "http://www.bafu.admin.ch/geodatenmodelle",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BAFU/replaced/Moorlandschaften_V1.ili",
  },
  {
    id: 587,
    mD5: "202f5b280ab31407406c7b4994b827a8",
    name: "Moorlandschaften_LV03_V1_1",
    schemaLanguage: "ili2_3",
    file: "BAFU/replaced/Moorlandschaften_V1_1.ili",
    version: "2017-03-27",
    publishingDate: "2018-08-12T22:00:00Z",
    dependsOnModel: ["GeometryCHLV03_V1"],
    tags: ["24.1"],
    shortDescription: null,
    issuer: "https://models.geo.admin.ch/BAFU/",
    technicalContact: "mailto:gis@bafu.admin.ch",
    furtherInformation: "https://www.bafu.admin.ch/geodatenmodelle",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BAFU/replaced/Moorlandschaften_V1_1.ili",
  },
  {
    id: 588,
    mD5: "202f5b280ab31407406c7b4994b827a8",
    name: "Moorlandschaften_LV95_V1_1",
    schemaLanguage: "ili2_3",
    file: "BAFU/replaced/Moorlandschaften_V1_1.ili",
    version: "2017-03-27",
    publishingDate: "2018-08-12T22:00:00Z",
    dependsOnModel: ["GeometryCHLV95_V1"],
    tags: ["24.1"],
    shortDescription: null,
    issuer: "https://models.geo.admin.ch/BAFU/",
    technicalContact: "mailto:gis@bafu.admin.ch",
    furtherInformation: "https://www.bafu.admin.ch/geodatenmodelle",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BAFU/replaced/Moorlandschaften_V1_1.ili",
  },
  {
    id: 783,
    mD5: "369bc420dcfbd5f9d16ed09462bdd325",
    name: "Moorlandschaften_V1_2",
    schemaLanguage: "ili2_3",
    file: "BAFU/Moorlandschaften_V1_2.ili",
    version: "2022-06-02",
    publishingDate: "2022-07-10T22:00:00Z",
    dependsOnModel: ["GeometryCHLV95_V1"],
    tags: ["24.1"],
    shortDescription: null,
    issuer: "https://models.geo.admin.ch/BAFU/",
    technicalContact: "mailto:gis@bafu.admin.ch",
    furtherInformation: "https://www.bafu.admin.ch/geodatenmodelle",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BAFU/Moorlandschaften_V1_2.ili",
  },
  {
    id: 1001,
    mD5: "ebce2b64aa0e659447fc694640ece91a",
    name: "PlanDirecteurEnergiesRenouvelables_V1",
    schemaLanguage: "ili2_3",
    file: "BFE/PlanDirecteurEnergiesRenouvelables_V1.ili",
    version: "2020-11-30",
    publishingDate: "2020-12-08T23:00:00Z",
    dependsOnModel: [
      "RichtplanungErneuerbareEnergien_V1",
      "GeometryCHLV95_V1",
      "CHAdminCodes_V1",
      "CatalogueObjects_V1",
    ],
    tags: [],
    shortDescription: null,
    issuer: "https://models.geo.admin.ch/BFE/",
    technicalContact: "mailto:info@bfe.admin.ch",
    furtherInformation: "https://www.bfe.admin.ch/geoinformation",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BFE/PlanDirecteurEnergiesRenouvelables_V1.ili",
  },
  {
    id: 1066,
    mD5: "3e44a68a2b389bee963cd23111fc3116",
    name: "Landwirtschaftliche_Zonengrenzen_V1_2",
    schemaLanguage: "ili2_3",
    file: "BLW/landwirtschaftliche_zonengrenzen_20140701.ili",
    version: "2014-07-01",
    publishingDate: "2014-09-15T22:00:00Z",
    dependsOnModel: ["GeometryCHLV03_V1", "Landwirtschaftliche_Zonengrenzen_Kataloge_V1_2"],
    tags: ["149.1"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BLW/",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation:
      "https://www.blw.admin.ch/blw/de/home/instrumente/grundlagen-und-querschnittsthemen/landwirtschaftliche-zonen.html",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/landwirtschaftliche_zonengrenzen_20140701.ili",
  },
  {
    id: 1067,
    mD5: "3e44a68a2b389bee963cd23111fc3116",
    name: "Landwirtschaftliche_Zonengrenzen_LV95_V1_2",
    schemaLanguage: "ili2_3",
    file: "BLW/landwirtschaftliche_zonengrenzen_20140701.ili",
    version: "2014-07-01",
    publishingDate: "2014-09-15T22:00:00Z",
    dependsOnModel: ["GeometryCHLV95_V1", "Landwirtschaftliche_Zonengrenzen_Kataloge_V1_2"],
    tags: ["149.1"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BLW/",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation:
      "https://www.blw.admin.ch/blw/de/home/instrumente/grundlagen-und-querschnittsthemen/landwirtschaftliche-zonen.html",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/landwirtschaftliche_zonengrenzen_20140701.ili",
  },
  {
    id: 1086,
    mD5: "7ebabd7beda3ae0d6f98e97ee6dc9323",
    name: "Bewirtschaftungseinheit_V1_2",
    schemaLanguage: "ili2_3",
    file: "BLW/replaced/bewirtschaftungseinheit_20140701.ili",
    version: "2016-04-15",
    publishingDate: "2016-04-14T22:00:00Z",
    dependsOnModel: [
      "CHAdminCodes_V1",
      "GeometryCHLV03_V1",
      "Landwirtschaftliche_Zonengrenzen_Kataloge_V1_2",
      "Bearbeitungsstatus_V1_2",
    ],
    tags: ["153.6"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BLW/",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation: "http://www.blw.admin.ch/dienstleistungen/00568/01328/01329/index.html?lang=de",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/replaced/bewirtschaftungseinheit_20140701.ili",
  },
  {
    id: 1087,
    mD5: "7ebabd7beda3ae0d6f98e97ee6dc9323",
    name: "Bewirtschaftungseinheit_LV95_V1_2",
    schemaLanguage: "ili2_3",
    file: "BLW/replaced/bewirtschaftungseinheit_20140701.ili",
    version: "2016-04-15",
    publishingDate: "2016-04-14T22:00:00Z",
    dependsOnModel: [
      "GeometryCHLV95_V1",
      "Bearbeitungsstatus_V1_2",
      "CHAdminCodes_V1",
      "Landwirtschaftliche_Zonengrenzen_Kataloge_V1_2",
    ],
    tags: ["153.6"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BLW/",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation: "http://www.blw.admin.ch/dienstleistungen/00568/01328/01329/index.html?lang=de",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/replaced/bewirtschaftungseinheit_20140701.ili",
  },
  {
    id: 1088,
    mD5: "31652db1f9fe8e7380751dd9b64abd13",
    name: "Elemente_mit_Landschaftsqualitaet_V1_2",
    schemaLanguage: "ili2_3",
    file: "BLW/replaced/elemente_mit_landschaftsqualitaet_20140701.ili",
    version: "2016-04-15",
    publishingDate: "2016-04-14T22:00:00Z",
    dependsOnModel: ["Bearbeitungsstatus_V1_2", "GeometryCHLV03_V1", "LocalisationCH_V1"],
    tags: ["153.8"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BLW/",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation: "http://www.blw.admin.ch/dienstleistungen/00568/01328/01329/index.html?lang=de",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/replaced/elemente_mit_landschaftsqualitaet_20140701.ili",
  },
  {
    id: 1089,
    mD5: "31652db1f9fe8e7380751dd9b64abd13",
    name: "Elemente_mit_Landschaftsqualitaet_LV95_V1_2",
    schemaLanguage: "ili2_3",
    file: "BLW/replaced/elemente_mit_landschaftsqualitaet_20140701.ili",
    version: "2016-04-15",
    publishingDate: "2016-04-14T22:00:00Z",
    dependsOnModel: ["Bearbeitungsstatus_V1_2", "GeometryCHLV95_V1", "LocalisationCH_V1"],
    tags: ["153.8"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BLW/",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation: "http://www.blw.admin.ch/dienstleistungen/00568/01328/01329/index.html?lang=de",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/replaced/elemente_mit_landschaftsqualitaet_20140701.ili",
  },
  {
    id: 1112,
    mD5: "baac5694f0f3ca30e5c2675ee4a45d3a",
    name: "Bewirtschaftungseinheit_LV95_V1_3",
    schemaLanguage: "ili2_3",
    file: "BLW/Bewirtschaftungseinheit_V1_3.ili",
    version: "2017-03-21",
    publishingDate: "2017-03-22T23:00:00Z",
    dependsOnModel: [
      "GeometryCHLV95_V1",
      "Bearbeitungsstatus_V1_2",
      "CHAdminCodes_V1",
      "Landwirtschaftliche_Zonengrenzen_Kataloge_V1_2",
    ],
    tags: ["153.6"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BLW/",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation:
      "https://www.blw.admin.ch/blw/de/home/politik/datenmanagement/geografisches-informationssystem-gis/minimale-geodatenmodelle.html",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/Bewirtschaftungseinheit_V1_3.ili",
  },
  {
    id: 1113,
    mD5: "baac5694f0f3ca30e5c2675ee4a45d3a",
    name: "Bewirtschaftungseinheit_V1_3",
    schemaLanguage: "ili2_3",
    file: "BLW/Bewirtschaftungseinheit_V1_3.ili",
    version: "2017-03-21",
    publishingDate: "2017-03-22T23:00:00Z",
    dependsOnModel: [
      "CHAdminCodes_V1",
      "GeometryCHLV03_V1",
      "Landwirtschaftliche_Zonengrenzen_Kataloge_V1_2",
      "Bearbeitungsstatus_V1_2",
    ],
    tags: ["153.6"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BLW/",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation:
      "https://www.blw.admin.ch/blw/de/home/politik/datenmanagement/geografisches-informationssystem-gis/minimale-geodatenmodelle.html",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/Bewirtschaftungseinheit_V1_3.ili",
  },
  {
    id: 1119,
    mD5: "f92dde56e3b06e3488247d9396755bd5",
    name: "Elemente_mit_Landschaftsqualitaet_LV95_V1_3",
    schemaLanguage: "ili2_3",
    file: "BLW/Elemente_mit_Landschaftsqualitaet_V1_3.ili",
    version: "2017-03-21",
    publishingDate: "2017-03-22T23:00:00Z",
    dependsOnModel: ["Bearbeitungsstatus_V1_2", "GeometryCHLV95_V1", "LocalisationCH_V1"],
    tags: ["153.8"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BLW/",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation:
      "https://www.blw.admin.ch/blw/de/home/politik/datenmanagement/geografisches-informationssystem-gis/minimale-geodatenmodelle.html",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/Elemente_mit_Landschaftsqualitaet_V1_3.ili",
  },
  {
    id: 1120,
    mD5: "f92dde56e3b06e3488247d9396755bd5",
    name: "Elemente_mit_Landschaftsqualitaet_V1_3",
    schemaLanguage: "ili2_3",
    file: "BLW/Elemente_mit_Landschaftsqualitaet_V1_3.ili",
    version: "2017-03-21",
    publishingDate: "2017-03-22T23:00:00Z",
    dependsOnModel: ["Bearbeitungsstatus_V1_2", "GeometryCHLV03_V1", "LocalisationCH_V1"],
    tags: ["153.8"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BLW/",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation:
      "https://www.blw.admin.ch/blw/de/home/politik/datenmanagement/geografisches-informationssystem-gis/minimale-geodatenmodelle.html",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/Elemente_mit_Landschaftsqualitaet_V1_3.ili",
  },
  {
    id: 1135,
    mD5: "3e44a68a2b389bee963cd23111fc3116",
    name: "Landwirtschaftliche_Zonengrenzen_Kataloge_V1_2",
    schemaLanguage: "ili2_3",
    file: "BLW/landwirtschaftliche_zonengrenzen_20140701.ili",
    version: "2020-08-26",
    publishingDate: "2020-08-25T22:00:00Z",
    dependsOnModel: ["CatalogueObjects_V1", "LocalisationCH_V1"],
    tags: ["149.1"],
    shortDescription: null,
    issuer: "http://models.geo.admin.ch/BLW/",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation:
      "http://https://www.blw.admin.ch/blw/de/home/instrumente/grundlagen-und-querschnittsthemen/landwirtschaftliche-zonen.html",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/landwirtschaftliche_zonengrenzen_20140701.ili",
  },
  {
    id: 1136,
    mD5: "d57fec40bdc6c76ac9b102f715cee1b6",
    name: "Landwirtschaftliche_Zonengrenzen_V1",
    schemaLanguage: "ili2_3",
    file: "BLW/replaced/zonengrenzen_20120601.ili",
    version: "2020-08-26",
    publishingDate: "2020-08-25T22:00:00Z",
    dependsOnModel: ["GeometryCHLV03_V1", "CatalogueObjects_V1", "LocalisationCH_V1"],
    tags: ["149.1"],
    shortDescription: null,
    issuer: "http://www.blw.admin.ch",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation:
      "https://www.blw.admin.ch/blw/de/home/instrumente/grundlagen-und-querschnittsthemen/landwirtschaftliche-zonen.html",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/replaced/zonengrenzen_20120601.ili",
  },
  {
    id: 1137,
    mD5: "d57fec40bdc6c76ac9b102f715cee1b6",
    name: "Landwirtschaftliche_Zonengrenzen_LV95_V1",
    schemaLanguage: "ili2_3",
    file: "BLW/replaced/zonengrenzen_20120601.ili",
    version: "2020-08-26",
    publishingDate: "2020-08-25T22:00:00Z",
    dependsOnModel: ["GeometryCHLV95_V1", "CatalogueObjects_V1", "LocalisationCH_V1"],
    tags: ["149.1"],
    shortDescription: null,
    issuer: "http://www.blw.admin.ch",
    technicalContact: "mailto:info@blw.admin.ch",
    furtherInformation:
      "https://www.blw.admin.ch/blw/de/home/instrumente/grundlagen-und-querschnittsthemen/landwirtschaftliche-zonen.html",
    modelRepository: {
      hostNameId: "models.geo.admin.ch",
      uri: "https://models.geo.admin.ch/",
      name: "models.geo.admin.ch",
      title: "Geobasisdaten-Modell-Ablage",
      shortDescription: "Modell-Ablage fuer Datenmodelle der Geobasisdaten des Bundesrechts",
      owner: "http://www.geo.admin.ch",
      technicalContact: "mailto:models@geo.admin.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.admin.ch/BLW/replaced/zonengrenzen_20120601.ili",
  },
  {
    id: 1587,
    mD5: "9d95686ac8ba94294d8291b510f6761a",
    name: "GL_LwLandschaftsqualitaet_Publikation_V1",
    schemaLanguage: "ili2_3",
    file: "ili/GL_LwLandschaftsqualitaet_Publikation_V1_2021-02-10.ili",
    version: "2021-02-10",
    publishingDate: "0001-01-01T00:00:00",
    dependsOnModel: ["GeometryCHLV95_V1", "Units"],
    tags: [],
    shortDescription: null,
    issuer: "https://www.gl.ch",
    technicalContact: "mailto:geoinformation@gl.ch",
    furtherInformation: null,
    modelRepository: {
      hostNameId: "models.geo.gl.ch",
      uri: "https://models.geo.gl.ch/",
      name: "https://models.geo.gl.ch",
      title: "Datenmodellablage des Kantons Glarus",
      shortDescription:
        "Datenmodellablage des Kantons Glarus. Datenmodelle des Bundesrechts (Zuständigkeit Kanton, Gemeinden), des kantonalen Rechts (Zuständigkeit Kanton, Gemeinden) und des kommunalen Rechts (Zuständigkeit Gemeinden).",
      owner: "mailto:geoinformation@gl.ch",
      technicalContact: "mailto:geoinformation@gl.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.gl.ch/ili/GL_LwLandschaftsqualitaet_Publikation_V1_2021-02-10.ili",
  },
  {
    id: 1626,
    mD5: "424b9d7db55e466660114df0573f059a",
    name: "GL_Landschaftsverzeichnis_Publikation_V1",
    schemaLanguage: "ili2_3",
    file: "ili/GL_Landschaftsverzeichnis_Publikation_2021-08-04.ili",
    version: "2021-08-04",
    publishingDate: "0001-01-01T00:00:00",
    dependsOnModel: ["GeometryCHLV95_V1"],
    tags: [],
    shortDescription: null,
    issuer: "https://www.gl.ch",
    technicalContact: "mailto:geoinformation@gl.ch",
    furtherInformation: null,
    modelRepository: {
      hostNameId: "models.geo.gl.ch",
      uri: "https://models.geo.gl.ch/",
      name: "https://models.geo.gl.ch",
      title: "Datenmodellablage des Kantons Glarus",
      shortDescription:
        "Datenmodellablage des Kantons Glarus. Datenmodelle des Bundesrechts (Zuständigkeit Kanton, Gemeinden), des kantonalen Rechts (Zuständigkeit Kanton, Gemeinden) und des kommunalen Rechts (Zuständigkeit Gemeinden).",
      owner: "mailto:geoinformation@gl.ch",
      technicalContact: "mailto:geoinformation@gl.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.gl.ch/ili/GL_Landschaftsverzeichnis_Publikation_2021-08-04.ili",
  },
  {
    id: 1707,
    mD5: "53f03d6b282898cba2a00fcf3a1f6e0e",
    name: "SO_ALW_Landwirtschaftliche_Zonengrenzen_Publikation_20200630",
    schemaLanguage: "ili2_3",
    file: "ALW/SO_ALW_Landwirtschaftliche_Zonengrenzen_Publikation_20200630.ili",
    version: "2020-06-30",
    publishingDate: "0001-01-01T00:00:00",
    dependsOnModel: ["GeometryCHLV95_V1"],
    tags: [],
    shortDescription: null,
    issuer: "http://geo.so.ch/models/ALW",
    technicalContact: "mailto:agi@so.ch",
    furtherInformation: null,
    modelRepository: {
      hostNameId: "geo.so.ch",
      uri: "https://geo.so.ch/models/",
      name: "models.geo.so.ch",
      title: "ModelRepository Kantons Solothurn",
      shortDescription: "Modellablage fuer Datenmodelle der Geobasisdaten des kantonalen Rechts des Kantons Solothurn ",
      owner: "https://geo.so.ch",
      technicalContact: "mailto:agi@bd.so.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://geo.so.ch/models/ALW/SO_ALW_Landwirtschaftliche_Zonengrenzen_Publikation_20200630.ili",
  },
  {
    id: 1720,
    mD5: "234e6296ce4fe367b2fd5a47a5513815",
    name: "SO_ALW_Landwirtschaft_Tierhaltung_Publikation_20211019",
    schemaLanguage: "ili2_3",
    file: "ALW/SO_ALW_Landwirtschaft_Tierhaltung_Publikation_20211019.ili",
    version: "2021-10-19",
    publishingDate: "0001-01-01T00:00:00",
    dependsOnModel: ["CHAdminCodes_V1", "GeometryCHLV95_V1"],
    tags: [],
    shortDescription: null,
    issuer: "http://geo.so.ch/models/ALW",
    technicalContact: "mailto:agi@bd.so.ch",
    furtherInformation: "http://geo.so.ch/models/ALW/SO_ALW_Landwirtschaft_Tierhaltung_Publikation_20210315.uml",
    modelRepository: {
      hostNameId: "geo.so.ch",
      uri: "https://geo.so.ch/models/",
      name: "models.geo.so.ch",
      title: "ModelRepository Kantons Solothurn",
      shortDescription: "Modellablage fuer Datenmodelle der Geobasisdaten des kantonalen Rechts des Kantons Solothurn ",
      owner: "https://geo.so.ch",
      technicalContact: "mailto:agi@bd.so.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://geo.so.ch/models/ALW/SO_ALW_Landwirtschaft_Tierhaltung_Publikation_20211019.ili",
  },
  {
    id: 1721,
    mD5: "234e6296ce4fe367b2fd5a47a5513815",
    name: "SO_ALW_Landwirtschaft_Tierhaltung_Publikation_restricted_20211019",
    schemaLanguage: "ili2_3",
    file: "ALW/SO_ALW_Landwirtschaft_Tierhaltung_Publikation_20211019.ili",
    version: "2021-10-19",
    publishingDate: "0001-01-01T00:00:00",
    dependsOnModel: ["SO_ALW_Landwirtschaft_Tierhaltung_Publikation_20211019"],
    tags: [],
    shortDescription: null,
    issuer: "http://geo.so.ch/models/ALW",
    technicalContact: "mailto:agi@bd.so.ch",
    furtherInformation: null,
    modelRepository: {
      hostNameId: "geo.so.ch",
      uri: "https://geo.so.ch/models/",
      name: "models.geo.so.ch",
      title: "ModelRepository Kantons Solothurn",
      shortDescription: "Modellablage fuer Datenmodelle der Geobasisdaten des kantonalen Rechts des Kantons Solothurn ",
      owner: "https://geo.so.ch",
      technicalContact: "mailto:agi@bd.so.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://geo.so.ch/models/ALW/SO_ALW_Landwirtschaft_Tierhaltung_Publikation_20211019.ili",
  },
  {
    id: 1722,
    mD5: "42e4841dca41dd4157c09aa81beb58d0",
    name: "SO_ALW_Landwirtschaft_Tierhaltung_20210426",
    schemaLanguage: "ili2_3",
    file: "ALW/SO_ALW_Landwirtschaft_Tierhaltung_20210426.ili",
    version: "2021-03-15",
    publishingDate: "0001-01-01T00:00:00",
    dependsOnModel: ["CHAdminCodes_V1", "GeometryCHLV95_V1"],
    tags: [],
    shortDescription: null,
    issuer: "https://alw.so.ch",
    technicalContact: "mailto:agi@bd.so.ch",
    furtherInformation: "http://geo.so.ch/models/ALW/SO_ALW_Landwirtschaft_Tierhaltung_20210315.uml",
    modelRepository: {
      hostNameId: "geo.so.ch",
      uri: "https://geo.so.ch/models/",
      name: "models.geo.so.ch",
      title: "ModelRepository Kantons Solothurn",
      shortDescription: "Modellablage fuer Datenmodelle der Geobasisdaten des kantonalen Rechts des Kantons Solothurn ",
      owner: "https://geo.so.ch",
      technicalContact: "mailto:agi@bd.so.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://geo.so.ch/models/ALW/SO_ALW_Landwirtschaft_Tierhaltung_20210426.ili",
  },
  {
    id: 1728,
    mD5: "2dd59e2209de0c0e67ce68fb430b1686",
    name: "SO_KSTA_Landwert_20210202",
    schemaLanguage: "ili2_3",
    file: "KSTA/SO_KSTA_Landwert_20210202.ili",
    version: "2021-02-02",
    publishingDate: "0001-01-01T00:00:00",
    dependsOnModel: ["GeometryCHLV95_V1"],
    tags: [],
    shortDescription: null,
    issuer: "http://www.geo.so.ch/models/KSTA",
    technicalContact: "mailto:agi@bd.so.ch",
    furtherInformation: null,
    modelRepository: {
      hostNameId: "geo.so.ch",
      uri: "https://geo.so.ch/models/",
      name: "models.geo.so.ch",
      title: "ModelRepository Kantons Solothurn",
      shortDescription: "Modellablage fuer Datenmodelle der Geobasisdaten des kantonalen Rechts des Kantons Solothurn ",
      owner: "https://geo.so.ch",
      technicalContact: "mailto:agi@bd.so.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://geo.so.ch/models/KSTA/SO_KSTA_Landwert_20210202.ili",
  },
  {
    id: 1963,
    mD5: "59BEF803CD868782C4B69C2C2197873D",
    name: "SZ_Strukturverbesserungen_Landwirtschaft_20190320",
    schemaLanguage: "ili2_3",
    file: "AFL/replaced/SZ_Strukturverbesserungen_Landwirtschaft_2019-03-20.ili",
    version: "2019-03-20",
    publishingDate: "2019-03-31T22:00:00Z",
    dependsOnModel: ["Units"],
    tags: [],
    shortDescription:
      "Dieses Modell beinhaltet die kantonalen Erweiterungen zum Modell\r\n          Strukturverbesserungen_LV95_V2 der Suissemelio",
    issuer: "http://models.geo.sz.ch",
    technicalContact: "mailto:geoportal@sz.ch",
    furtherInformation: null,
    modelRepository: {
      hostNameId: "models.geo.sz.ch",
      uri: "https://models.geo.sz.ch/",
      name: "models.geo.sz.ch",
      title: "Geodaten-Modell-Ablage des Kantons Schwyz",
      shortDescription:
        "Modell-Ablage für Datenmodelle der Geodaten des Kantons Schwyz. Die Ablage beinhaltet sowohl die Modelle der Geobasisdaten des Kantons Schwyz als auch weitere Datenmodelle von Geodaten.",
      owner: "http://www.geo.sz.ch",
      technicalContact: "mailto:geoportal@sz.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.sz.ch/AFL/replaced/SZ_Strukturverbesserungen_Landwirtschaft_2019-03-20.ili",
  },
  {
    id: 1964,
    mD5: "53008F262218E86308A79C4428F5BD8D",
    name: "SZ_Strukturverbesserungen_Landwirtschaft_20190417",
    schemaLanguage: "ili2_3",
    file: "AFL/replaced/SZ_Strukturverbesserungen_Landwirtschaft_2019-04-17.ili",
    version: "2019-05-29",
    publishingDate: "2019-04-17T22:00:00Z",
    dependsOnModel: ["Units"],
    tags: [],
    shortDescription:
      "Dieses Modell beinhaltet die kantonalen Erweiterungen zum Modell\r\n          Strukturverbesserungen_LV95_V2 der Suissemelio",
    issuer: "http://models.geo.sz.ch",
    technicalContact: "mailto:geoportal@sz.ch",
    furtherInformation: null,
    modelRepository: {
      hostNameId: "models.geo.sz.ch",
      uri: "https://models.geo.sz.ch/",
      name: "models.geo.sz.ch",
      title: "Geodaten-Modell-Ablage des Kantons Schwyz",
      shortDescription:
        "Modell-Ablage für Datenmodelle der Geodaten des Kantons Schwyz. Die Ablage beinhaltet sowohl die Modelle der Geobasisdaten des Kantons Schwyz als auch weitere Datenmodelle von Geodaten.",
      owner: "http://www.geo.sz.ch",
      technicalContact: "mailto:geoportal@sz.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.sz.ch/AFL/replaced/SZ_Strukturverbesserungen_Landwirtschaft_2019-04-17.ili",
  },
  {
    id: 1965,
    mD5: "57F3DC91844490A7A578C376DB5826C3",
    name: "SZ_Strukturverbesserungen_Landwirtschaft_20191113",
    schemaLanguage: "ili2_3",
    file: "AFL/SZ_Strukturverbesserungen_Landwirtschaft_2019-11-13.ili",
    version: "2019-11-13",
    publishingDate: "2019-12-15T23:00:00Z",
    dependsOnModel: ["Units"],
    tags: [],
    shortDescription:
      "Dieses Modell beinhaltet die kantonalen Erweiterungen zum Modell\r\n          Strukturverbesserungen_LV95_V2 der Suissemelio",
    issuer: "http://models.geo.sz.ch",
    technicalContact: "mailto:geoportal@sz.ch",
    furtherInformation: null,
    modelRepository: {
      hostNameId: "models.geo.sz.ch",
      uri: "https://models.geo.sz.ch/",
      name: "models.geo.sz.ch",
      title: "Geodaten-Modell-Ablage des Kantons Schwyz",
      shortDescription:
        "Modell-Ablage für Datenmodelle der Geodaten des Kantons Schwyz. Die Ablage beinhaltet sowohl die Modelle der Geobasisdaten des Kantons Schwyz als auch weitere Datenmodelle von Geodaten.",
      owner: "http://www.geo.sz.ch",
      technicalContact: "mailto:geoportal@sz.ch",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.sz.ch/AFL/SZ_Strukturverbesserungen_Landwirtschaft_2019-11-13.ili",
  },
  {
    id: 2148,
    mD5: "B531124E66B427CA58257D1791A2BF4F",
    name: "Landschaftsschutzgebiete_LI_V1",
    schemaLanguage: "ili2_3",
    file: "AU/Landschaftsschutzgebiete_LI_V1.ili",
    version: "2019-07-04",
    publishingDate: "0001-01-01T00:00:00",
    dependsOnModel: ["Units", "LI_Base_V1", "GeometryLILV95_V1", "CoordSys"],
    tags: [],
    shortDescription: null,
    issuer: null,
    technicalContact: null,
    furtherInformation: null,
    modelRepository: {
      hostNameId: "models.geo.llv.li",
      uri: "https://models.geo.llv.li/",
      name: "models.geo.llv.li",
      title: "ModelRepository Liechtenstein",
      shortDescription: "Modell-Ablage der GDI-Liechtenstein",
      owner: "https://www.llv.li",
      technicalContact: "mailto:geodaten@llv.li",
      subsidiarySites: [],
      parentSites: [],
      catalogs: [],
    },
    uri: "https://models.geo.llv.li/AU/Landschaftsschutzgebiete_LI_V1.ili",
  },
];
